packageExtensions:
  "@0x/base-contract@*":
    dependencies:
      "ethereum-types": "*"
  "@0x/utils@*":
    dependencies:
      "ethereum-types": "*"
  "@traderxyz/nft-swap-sdk@*":
    dependencies:
      "@ethersproject/address": "*"
  "ethereumjs-blockchain@*":
    dependencies:
      "bn.js": "*"
  "ethereumjs-vm@*":
    dependencies:
      "bn.js": "*"
      "rlp": "*"
  "opensea-js@*":
    dependencies:
      "ethereum-types": "*"
  "wyvern-schemas@*":
    dependencies:
      "ethereumjs-abi": "*"
      "ethereum-types": "*"
      "ethereumjs-util": "*"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
